import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/61wkyN+MZfL._UL1500_.jpg",
    title: "Titan Analog Black Dial",
    star: <AiFillStar className="rating-star" />,
    reviews: "(112 reviews)",
    prevPrice: "₹10,495",
    newPrice: "₹9,760",
    company: "Titan ",
    color: "Black",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/71J0ySHdO1L._UX425_.jpg",
    title: "Casio Analog Blue Dial Men's",
    star: <AiFillStar className="rating-star"/>,
    reviews: "(150 reviews)",
    prevPrice: "₹10,995",
    newPrice: "₹5,497",
    company: "Casio",
    color: "Silver",
    category: "Analog",
  },

  {
    img: "https://m.media-amazon.com/images/I/618fpS1lonL._SL1500_.jpg",
    title: "boAt Wave Style Smart Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(129 reviews)",
    prevPrice: "₹5,990",
    newPrice: "₹999",
    company: "boAt",
    color: "Black",
    category: "Smart Watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/61aVQDazNHL._SL1500_.jpg",
    title: "Samsung Galaxy Watch5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(183 reviews)",
    prevPrice: "₹33,999",
    newPrice: "₹30,999",
    company: "Samsung",
    color: "black",
    category: "Smart Watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/61FKVerMRWL._UL1100_.jpg",
    title: "Casio Enticer Analog Dial Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "₹15,995",
    newPrice: "₹5,995",
    company: "Casio",
    color: "Silver",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/61zDNEO991L._UL1100_.jpg",
    title: "Casio Analog Silver Dial",
    star: <AiFillStar className="rating-star" />,
    reviews: "(133 reviews)",
    prevPrice: "₹2,395",
    newPrice: "₹1,796",
    company: "Adidas",
    color: "Silver",
    category: "Analog",
  },

  {
    img: "https://m.media-amazon.com/images/I/71XSLNECruL._SL1500_.jpg",
    title: "Samsung Galaxy Watch6 LTE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: "₹41,999",
    newPrice: "₹36,999",
    company: "Samsung",
    color: "white",
    category: "Smart Watch",
  },

  {
    img: "https://m.media-amazon.com/images/I/61w3nZPUflL._UL1100_.jpg",
    title: "Casio Edifice Analog EFS-S570DC",
    star: <AiFillStar className="rating-star" />,
    reviews: "(197 reviews)",
    prevPrice: "₹20,495",
    newPrice: "₹18,445",
    company: "Casio",
    color: "Silver",
    category: "Analog",
  },

  {
    img: "https://m.media-amazon.com/images/I/71WTVuds6pL._SL1500_.jpg",
    title: "boAt Wave Active Smart Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(211 reviews)",
    prevPrice: "₹6,499",
    newPrice: "₹1,599",
    company: "boAt",
    color: "Rose pink",
    category: "Smart Watch",
  },

  {
    img: "https://m.media-amazon.com/images/I/61L4SkS7w2L._SL1500_.jpg",
    title: "boAt Rockerz 558 Bluetooth Wireless",
    star: <AiFillStar className="rating-star" />,
    reviews: "(161 reviews)",
    prevPrice: "₹4,999",
    newPrice: " ₹1,999",
    company: "boAt",
    color: "Red",
    category: "Headphones",
  },
  {
    img: "https://m.media-amazon.com/images/I/61KNJav3S9L._SL1500_.jpg",
    title: "boAt Airdopes 141",
    star: <AiFillStar className="rating-star" />,
    reviews: "(109 reviews)",
    prevPrice: "₹4,490",
    newPrice: "₹1,299",
    company: "boAt",
    color: "Black",
    category: "Headphones",
  },
  {
    img: "https://m.media-amazon.com/images/I/61kLSSQ6P7L._SL1128_.jpg",
    title: "Sony MDR-ZX110AP",
    star: <AiFillStar className="rating-star" />,
    reviews: "(138 reviews)",
    prevPrice: "₹3,090",
    newPrice: "₹1,490",
    company: "Sony",
    color: "black",
    category: "Headphones",
  },
  {
    img: "https://m.media-amazon.com/images/I/51v7Y75v0LL._SL1500_.jpg",
    title: "Sony WI-C100",
    star: <AiFillStar className="rating-star" />,
    reviews: "(176 reviews)",
    prevPrice: "₹2,790",
    newPrice: "₹1,649",
    company: "Sony",
    color: "black",
    category: "Headphones",
  },
  {
    img: "https://m.media-amazon.com/images/I/611I0f+I+MS._UL1000_.jpg",
    title: "Fossil Analog Rose Gold",
    star: <AiFillStar className="rating-star" />,
    reviews: "(185 reviews)",
    prevPrice: "₹11,995",
    newPrice: "₹7,197",
    company: "TIMEX",
    color: "Gold",
    category: "Fossil",
  },

  {
    img: "https://m.media-amazon.com/images/I/61jm1Zq58FL._UL1500_.jpg",
    title: "Fossil Blue Analog Men's Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: "₹11,995",
    newPrice: "₹9,596",
    company: "Fossil",
    color: "Blue",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/71NoqVbq8sL._UL1500_.jpg",
    title: "Fossil Fb-01 Women's Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(174 reviews)",
    prevPrice: "₹12,525",
    newPrice: "₹9,995",
    company: "Fossil",
    color: "Grey",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/71B3z-7EWQL._SL1500_.jpg",
    title: "Fossil Gen 6",
    star: <AiFillStar className="rating-star" />,
    reviews: "(155 reviews)",
    prevPrice: "₹35,299",
    newPrice: "₹23,995",
    company: "Fossil",
    color: "Black",
    category: "Smart Watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/51w-FWqI2LL._UL1000_.jpg",
    title: "Fossil Neutra Automatic Analogue",
    star: <AiFillStar className="rating-star" />,
    reviews: "(168 reviews)",
    prevPrice: "₹19,995",
    newPrice: "₹15,996",
    company: "Fossil",
    color: "Black",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/61WkDUtq5aL._UL1500_.jpg",
    title: "Titan Analog 90102QM01",
    star: <AiFillStar className="rating-star" />,
    reviews: "(139 reviews)",
    prevPrice: "₹12,645",
    newPrice: "₹11,380",
    company: "Titan",
    color: "Blue",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/61NYXFj6KcL._UL1500_.jpg",
    title: "Titan Metal Mechanicals",
    star: <AiFillStar className="rating-star" />,
    reviews: "(147 reviews)",
    prevPrice: "₹23,995",
    newPrice: "₹22,995",
    company: "Titan",
    color: "Black",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/5185j4WEUZL._UL1000_.jpg",
    title: "Titan Analog 95203WM01",
    star: <AiFillStar className="rating-star" />,
    reviews: "(200 reviews)",
    prevPrice: "₹16,195",
    newPrice: "₹11,295",
    company: "Titan",
    color: "Gold",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/71ieP9T7gRL._UL1500_.jpg",
    title: "Titan Analog 2675WM01",
    star: <AiFillStar className="rating-star" />,
    reviews: "(201 reviews)",
    prevPrice: "₹28,995",
    newPrice: "₹22,995",
    company: "Titan",
    color: "Gold",
    category: "Analog",
  },
  {
    img: "https://m.media-amazon.com/images/I/61aqxElai2L._UL1500_.jpg",
    title: "Titan New Talk Smart Watch",
    star: <AiFillStar className="rating-star" />,
    reviews: "(129 reviews)",
    prevPrice: "₹34,995",
    newPrice: "₹14,995",
    company: "Titan",
    color: "Black",
    category: "Smart Watch",
  },

  {
    img: "https://m.media-amazon.com/images/I/61U1+VOFtML._SL1500_.jpg",
    title: "ColorFit Pulse 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(153 reviews)",
    prevPrice: "₹6,999",
    newPrice: "₹1,599",
    company: "Noise",
    color: "Black",
    category: "Smart Watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/51SnB1u-RVL._SL1500_.jpg",
    title: "Noise Buds VS201",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹2,999",
    newPrice: "₹1,499",
    company: "Noise",
    color: "White",
    category: "Headphones",
  },
  {
    img: "https://m.media-amazon.com/images/I/71hUqNCL-zL._SL1500_.jpg",
    title: "Noise ColorFit Ultra 3",
    star: <AiFillStar className="rating-star" />,
    reviews: "(109 reviews)",
    prevPrice: "₹8,999",
    newPrice: "₹4,999",
    company: "Noise",
    color: "Silver",
    category: "Smart Watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/61n4MZgN8mL._SL1500_.jpg",
    title: "Noise Arc Round Dial",
    star: <AiFillStar className="rating-star" />,
    reviews: "(88 reviews)",
    prevPrice: "₹4,999",
    newPrice: "₹1,499",
    company: "Noise",
    color: "Blue",
    category: "Smart Watch",
  },
  {
    img: "https://m.media-amazon.com/images/I/618mFEP9mTL._SL1500_.jpg",
    title: "ColorFit Pulse Grand",
    star: <AiFillStar className="rating-star" />,
    reviews: "(143 reviews)",
    prevPrice: "₹3,999",
    newPrice: "₹1,499",
    company: "Noise",
    color: "Rose pink",
    category: "Smart Watch",
  },
];

export default data;
